# Generated by Django 6.0.3 on 2026-03-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=500, unique=True)),
                ('seed_keyword', models.CharField(blank=True, db_index=True, max_length=255)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('competition', models.FloatField(blank=True, help_text='0.0 (low) to 1.0 (high)', null=True)),
                ('intent', models.CharField(choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('commercial', 'Commercial'), ('navigational', 'Navigational')], default='informational', max_length=20)),
                ('difficulty_score', models.FloatField(blank=True, help_text='0–100 difficulty score', null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_keyword', models.CharField(db_index=True, max_length=255)),
                ('total_keywords', models.IntegerField(default=0)),
                ('total_clusters', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='sessions', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
